name: velpa
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>3.1.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.5
  google_sign_in: ^6.2.1
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  crypto: ^3.0.1
  rxdart: ^0.27.3
  font_awesome_flutter: ^10.1.0
  uuid: ^4.3.3
  location: ^5.0.3
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  flutter_map_location_marker: ^9.0.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
