name: velpa
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.5
  google_sign_in: ^5.2.4
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  crypto: ^3.0.1
  rxdart: ^0.27.3
  provider: ^6.0.2
  font_awesome_flutter: ^10.1.0
  uuid: ^3.0.7
  google_maps_flutter: ^2.4.0
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
